create database  data_project;
USE data_project;

CREATE TABLE hotel_data (
    hotel VARCHAR(50),
    is_canceled TINYINT,
    lead_time INT,
    arrival_date_year INT,
    arrival_date_month VARCHAR(20),
    arrival_date_week_number INT,
    arrival_date_day_of_month INT,
    stays_in_weekend_nights INT,
    stays_in_week_nights INT,
    adults INT,
    children INT,
    babies INT,
    meal VARCHAR(20),
    country VARCHAR(10),
    market_segment VARCHAR(50),
    distribution_channel VARCHAR(50),
    is_repeated_guest TINYINT,
    previous_cancellations INT,
    previous_bookings_not_canceled INT,
    reserved_room_type VARCHAR(5),
    assigned_room_type VARCHAR(5),
    booking_changes INT,
    deposit_type VARCHAR(50),
    agent VARCHAR(20),
    company VARCHAR(20),
    days_in_waiting_list INT,
    customer_type VARCHAR(30),
    adr FLOAT,
    required_car_parking_spaces INT,
    total_of_special_requests INT,
    reservation_status VARCHAR(50),
    reservation_status_date DATE
);

CREATE TABLE hr_data (
    Employee_Name VARCHAR(100),
    EmpID INT PRIMARY KEY,
    MarriedID TINYINT,
    MaritalStatusID TINYINT,
    GenderID TINYINT,
    EmpStatusID TINYINT,
    DeptID INT,
    PerfScoreID INT,
    FromDiversityJobFairID TINYINT,
    Salary FLOAT,
    Termd TINYINT,
    PositionID INT,
    Position VARCHAR(100),
    State VARCHAR(10),
    Zip VARCHAR(10),
    DOB DATE,
    Sex CHAR(1),
    MaritalDesc VARCHAR(30),
    CitizenDesc VARCHAR(30),
    HispanicLatino VARCHAR(10),
    RaceDesc VARCHAR(30),
    DateofHire DATE,
    DateofTermination DATE,
    TermReason VARCHAR(50),
    EmploymentStatus VARCHAR(50),
    Department VARCHAR(50),
    ManagerName VARCHAR(100),
    ManagerID INT,
    RecruitmentSource VARCHAR(50),
    PerformanceScore VARCHAR(50),
    EngagementSurvey FLOAT,
    EmpSatisfaction INT,
    SpecialProjectsCount INT,
    LastPerformanceReview_Date DATE,
    DaysLateLast30 INT,
    Absences INT
);

